# generated by datamodel-codegen:
#   filename:  queryable.yaml
#   timestamp: 2025-09-30T19:52:59+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class Id(BaseModel):
    description: str
    type: str


class Title(BaseModel):
    description: str
    type: str


class Description(BaseModel):
    description: str
    type: str


class Language(BaseModel):
    description: str
    type: str


class Type(BaseModel):
    description: str
    type: str
    enum: List[str]


class SpatialTypes(BaseModel):
    description: str
    type: str
    enum: List[str]


class TemporalTypes(BaseModel):
    description: str
    type: str
    enum: List[str]


class Links(BaseModel):
    description: str
    type: str


class Properties1(BaseModel):
    id: Id
    title: Title
    description: Description
    language: Language
    type: Type
    spatial_types: SpatialTypes = Field(..., alias='spatial-types')
    temporal_types: TemporalTypes = Field(..., alias='temporal-types')
    links: Links


class Items(BaseModel):
    type: str
    required: List[str]
    properties: Properties1


class Queryables(BaseModel):
    type: str
    items: Items


class Properties(BaseModel):
    queryables: Queryables


class Model(BaseModel):
    type: str
    required: List[str]
    properties: Properties
