# generated by datamodel-codegen:
#   filename:  queryable.yaml
#   timestamp: 2025-09-30T19:52:59+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class SpatialTypes(BaseModel):
    description: str
    type: str
    enum: List[str]


class TemporalTypes(BaseModel):
    description: str
    type: str
    enum: List[str]


class Properties(BaseModel):
    id: str
    title: Optional[str]=""
    description: Optional[str]=""
    language: Optional[str]=""
    type: str
    # spatial_types: SpatialTypes = Field(..., alias='spatial-types')
    # temporal_types: TemporalTypes = Field(..., alias='temporal-types')
    links: Optional[str]=""


class CollectionQueryables(BaseModel):
    queryables: List[Properties]


# class Model(BaseModel):
#    type: str
#    required: List[str]
#    properties: Properties
