# generated by datamodel-codegen:
#   filename:  queryable.yaml
#   timestamp: 2025-09-30T19:52:59+00:00

from __future__ import annotations

from typing import Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field

from pydggsapi.schemas.ogc_collections.schema import Property


class SpatialTypes(BaseModel):
    description: str
    type: str
    enum: List[str]


class TemporalTypes(BaseModel):
    description: str
    type: str
    enum: List[str]


class CollectionQueryables(BaseModel):
    schema_: str = Field("https://json-schema.org/draft/2020-12/schema", alias="$schema")
    id_: Optional[str] = Field(None, alias="$id")
    type: str = "object"
    properties: Dict[str, Property]

    model_config = ConfigDict(validate_by_name=True, validate_by_alias=True)

# class Model(BaseModel):
#    type: str
#    required: List[str]
#    properties: Properties
