# generated by datamodel-codegen:
#   filename:  queryable.yaml
#   timestamp: 2025-09-30T19:52:59+00:00

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel


class Properties1(BaseModel):
    readOnly: bool
    x_ogc_role: str
    type: str
    x_ogc_propertySeq: int


class Schema(BaseModel):
    schema: str
    id: str
    type: str = "Object"
    title: str
    description: str
    properties: Dict[str, Properties1]


