# generated by datamodel-codegen:
#   filename:  queryable.yaml
#   timestamp: 2025-09-30T19:52:59+00:00

from __future__ import annotations

from typing import Annotated, Dict, Optional

from pydantic import BaseModel
from fastapi.responses import JSONResponse

from pydggsapi.schemas.common_basemodel import CommonBaseModel, OmitIfNone


class Property(CommonBaseModel):
    type: str
    format: Annotated[Optional[str], OmitIfNone] = None
    title: Annotated[Optional[str], OmitIfNone] = None
    description: Annotated[Optional[str], OmitIfNone] = None
    language: Annotated[Optional[str], OmitIfNone] = None
    readOnly: Annotated[Optional[bool], OmitIfNone] = None
    x_ogc_role: Annotated[Optional[str], OmitIfNone] = None
    x_ogc_propertySeq: Annotated[Optional[int], OmitIfNone] = None


class JsonSchemaResponse(JSONResponse):
    media_type = "application/schema+json"
